name: Test ros_controllers
on:
  pull_request:
  push:
    branches:
      - noetic-devel

env:
  DOCKER_USER: Engineer
  DOCKER_PASSWORD: P@ssw0rd
  DOCKER_REGISTRY: https://docker.fibo.kmutt.ac.th
  IMAGE_NAME: docker.fibo.kmutt.ac.th/ros_controllers
  TAG_NAME: latest
jobs:
  push-image-to-fibo-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - uses: actions/checkout@v4 # first action : checkout source code
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG_NAME
    - name: Docker Push
      run: docker push $IMAGE_NAME:$TAG_NAME